services:
  - type: web
    name: inter-office-memo-system
    env: node
    plan: free
    buildCommand: npm install --include=dev && npx prisma generate && npm run build
    startCommand: npx prisma db push --accept-data-loss && node scripts/seed.js && npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: memo-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"

databases:
  - name: memo-db
    plan: free
    databaseName: memo_system
    user: memo_admin
